//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/_Prototype/Code/v002/System/GameInput/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""PlayerActions"",
            ""id"": ""0ae6a539-3cb4-4bc7-bca9-85110c6bae42"",
            ""actions"": [
                {
                    ""name"": ""MovePlayer"",
                    ""type"": ""Value"",
                    ""id"": ""6676b0ed-73ea-466a-a7cf-5f337f097c6a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseTool"",
                    ""type"": ""Button"",
                    ""id"": ""070e2233-1727-460f-8d1a-015c8cff2040"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenTools"",
                    ""type"": ""Button"",
                    ""id"": ""a0507506-a8be-4649-bbf2-a88ecd01c1fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Movement"",
                    ""id"": ""c424bb02-a20e-4457-9e2d-da94b74c0c95"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4cc387b6-bdba-4628-a1b4-2d1fdeeb12d3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7f6e51e0-a1f7-474b-a059-7ab8fc3441b4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b4b03cbe-7ef1-4a2d-8805-8fa6621e6ae9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5972dec4-892c-4dcc-93c4-1f7557a46ade"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovePlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7c121f2a-a253-4195-b14b-03f319a3c813"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UseTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65f339e7-d1f8-4e85-8906-15df95f02a81"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""OpenTools"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ToolSelecting"",
            ""id"": ""763b8d6b-a27f-458f-a3fa-bae821548044"",
            ""actions"": [
                {
                    ""name"": ""ChangeToolLeft"",
                    ""type"": ""Button"",
                    ""id"": ""0e47c76d-7e92-4886-a923-93dcc24e7a5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeToolRight"",
                    ""type"": ""Button"",
                    ""id"": ""ac9f9319-fe92-42ce-a701-16a9bc1fee93"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseTool"",
                    ""type"": ""Button"",
                    ""id"": ""5068ca2b-f419-41ab-a667-3d591ab335cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6587912e-2a38-4396-8e11-b06c37d18c55"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeToolLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e1884b4-e661-4476-bf6f-69e2c7c5e2cd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeToolRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91399090-98da-4ecd-8a2e-b654ca319a74"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerActions
        m_PlayerActions = asset.FindActionMap("PlayerActions", throwIfNotFound: true);
        m_PlayerActions_MovePlayer = m_PlayerActions.FindAction("MovePlayer", throwIfNotFound: true);
        m_PlayerActions_UseTool = m_PlayerActions.FindAction("UseTool", throwIfNotFound: true);
        m_PlayerActions_OpenTools = m_PlayerActions.FindAction("OpenTools", throwIfNotFound: true);
        // ToolSelecting
        m_ToolSelecting = asset.FindActionMap("ToolSelecting", throwIfNotFound: true);
        m_ToolSelecting_ChangeToolLeft = m_ToolSelecting.FindAction("ChangeToolLeft", throwIfNotFound: true);
        m_ToolSelecting_ChangeToolRight = m_ToolSelecting.FindAction("ChangeToolRight", throwIfNotFound: true);
        m_ToolSelecting_UseTool = m_ToolSelecting.FindAction("UseTool", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActions
    private readonly InputActionMap m_PlayerActions;
    private IPlayerActionsActions m_PlayerActionsActionsCallbackInterface;
    private readonly InputAction m_PlayerActions_MovePlayer;
    private readonly InputAction m_PlayerActions_UseTool;
    private readonly InputAction m_PlayerActions_OpenTools;
    public struct PlayerActionsActions
    {
        private @GameInput m_Wrapper;
        public PlayerActionsActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovePlayer => m_Wrapper.m_PlayerActions_MovePlayer;
        public InputAction @UseTool => m_Wrapper.m_PlayerActions_UseTool;
        public InputAction @OpenTools => m_Wrapper.m_PlayerActions_OpenTools;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActionsActions instance)
        {
            if (m_Wrapper.m_PlayerActionsActionsCallbackInterface != null)
            {
                @MovePlayer.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnMovePlayer;
                @MovePlayer.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnMovePlayer;
                @MovePlayer.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnMovePlayer;
                @UseTool.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnUseTool;
                @UseTool.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnUseTool;
                @UseTool.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnUseTool;
                @OpenTools.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnOpenTools;
                @OpenTools.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnOpenTools;
                @OpenTools.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnOpenTools;
            }
            m_Wrapper.m_PlayerActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovePlayer.started += instance.OnMovePlayer;
                @MovePlayer.performed += instance.OnMovePlayer;
                @MovePlayer.canceled += instance.OnMovePlayer;
                @UseTool.started += instance.OnUseTool;
                @UseTool.performed += instance.OnUseTool;
                @UseTool.canceled += instance.OnUseTool;
                @OpenTools.started += instance.OnOpenTools;
                @OpenTools.performed += instance.OnOpenTools;
                @OpenTools.canceled += instance.OnOpenTools;
            }
        }
    }
    public PlayerActionsActions @PlayerActions => new PlayerActionsActions(this);

    // ToolSelecting
    private readonly InputActionMap m_ToolSelecting;
    private IToolSelectingActions m_ToolSelectingActionsCallbackInterface;
    private readonly InputAction m_ToolSelecting_ChangeToolLeft;
    private readonly InputAction m_ToolSelecting_ChangeToolRight;
    private readonly InputAction m_ToolSelecting_UseTool;
    public struct ToolSelectingActions
    {
        private @GameInput m_Wrapper;
        public ToolSelectingActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ChangeToolLeft => m_Wrapper.m_ToolSelecting_ChangeToolLeft;
        public InputAction @ChangeToolRight => m_Wrapper.m_ToolSelecting_ChangeToolRight;
        public InputAction @UseTool => m_Wrapper.m_ToolSelecting_UseTool;
        public InputActionMap Get() { return m_Wrapper.m_ToolSelecting; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ToolSelectingActions set) { return set.Get(); }
        public void SetCallbacks(IToolSelectingActions instance)
        {
            if (m_Wrapper.m_ToolSelectingActionsCallbackInterface != null)
            {
                @ChangeToolLeft.started -= m_Wrapper.m_ToolSelectingActionsCallbackInterface.OnChangeToolLeft;
                @ChangeToolLeft.performed -= m_Wrapper.m_ToolSelectingActionsCallbackInterface.OnChangeToolLeft;
                @ChangeToolLeft.canceled -= m_Wrapper.m_ToolSelectingActionsCallbackInterface.OnChangeToolLeft;
                @ChangeToolRight.started -= m_Wrapper.m_ToolSelectingActionsCallbackInterface.OnChangeToolRight;
                @ChangeToolRight.performed -= m_Wrapper.m_ToolSelectingActionsCallbackInterface.OnChangeToolRight;
                @ChangeToolRight.canceled -= m_Wrapper.m_ToolSelectingActionsCallbackInterface.OnChangeToolRight;
                @UseTool.started -= m_Wrapper.m_ToolSelectingActionsCallbackInterface.OnUseTool;
                @UseTool.performed -= m_Wrapper.m_ToolSelectingActionsCallbackInterface.OnUseTool;
                @UseTool.canceled -= m_Wrapper.m_ToolSelectingActionsCallbackInterface.OnUseTool;
            }
            m_Wrapper.m_ToolSelectingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ChangeToolLeft.started += instance.OnChangeToolLeft;
                @ChangeToolLeft.performed += instance.OnChangeToolLeft;
                @ChangeToolLeft.canceled += instance.OnChangeToolLeft;
                @ChangeToolRight.started += instance.OnChangeToolRight;
                @ChangeToolRight.performed += instance.OnChangeToolRight;
                @ChangeToolRight.canceled += instance.OnChangeToolRight;
                @UseTool.started += instance.OnUseTool;
                @UseTool.performed += instance.OnUseTool;
                @UseTool.canceled += instance.OnUseTool;
            }
        }
    }
    public ToolSelectingActions @ToolSelecting => new ToolSelectingActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayerActionsActions
    {
        void OnMovePlayer(InputAction.CallbackContext context);
        void OnUseTool(InputAction.CallbackContext context);
        void OnOpenTools(InputAction.CallbackContext context);
    }
    public interface IToolSelectingActions
    {
        void OnChangeToolLeft(InputAction.CallbackContext context);
        void OnChangeToolRight(InputAction.CallbackContext context);
        void OnUseTool(InputAction.CallbackContext context);
    }
}
